/// <autosync enabled="true" />
/// <reference path="modernizr-2.6.2.js" />
/// <reference path="jquery-1.10.2.js" />
/// <reference path="bootstrap.js" />
/// <reference path="respond.js" />
/// <reference path="jquery.validate.js" />
/// <reference path="jquery.validate.unobtrusive.js" />
/// <reference path="../" />
/// <reference path="../" />
/// <reference path="../" />
/// <reference path="../" />
/// <reference path="../" />
/// <reference path="../" />
/// <reference path="../" />
/// <reference path="../" />
/// <reference path="../" />
/// <reference path="../" />
/// <reference path="../" />
/// <reference path="../" />
/// <reference path="../" />
/// <reference path="../" />
/// <reference path="../" />
/// <reference path="../" />
/// <reference path="../" />
/// <reference path="../" />
/// <reference path="../" />
/// <reference path="../" />
/// <reference path="../" />
/// <reference path="../" />
/// <reference path="../" />
/// <reference path="../" />
/// <reference path="../" />
/// <reference path="../" />
/// <reference path="../" />
/// <reference path="../" />
/// <reference path="../" />
/// <reference path="../" />
/// <reference path="../" />
/// <reference path="../" />
/// <reference path="../" />
/// <reference path="../" />
/// <reference path="../" />
/// <reference path="../" />
/// <reference path="createcard/blur.js" />
/// <reference path="../" />
/// <reference path="../" />
/// <reference path="createcard/bootstrap.js" />
/// <reference path="../" />
/// <reference path="createcard/fastblur.js" />
/// <reference path="../" />
/// <reference path="createcard/jquery-1.7.1.js" />
/// <reference path="../" />
/// <reference path="createcard/jquery-1.8.3.js" />
/// <reference path="../" />
/// <reference path="createcard/jquery-2.0.2.js" />
/// <reference path="../" />
/// <reference path="createcard/jquery.flippy.js" />
/// <reference path="../" />
/// <reference path="../" />
/// <reference path="createcard/jquery.simple-dtpicker.js" />
/// <reference path="../" />
/// <reference path="createcard/knockout-2.3.0.js" />
/// <reference path="../" />
/// <reference path="createcard/mcolorpicker.js" />
/// <reference path="../" />
/// <reference path="../" />
/// <reference path="createcard/min.blur.js" />
/// <reference path="createcard/stackblur.js" />
/// <reference path="../" />
/// <reference path="../images/новая папка/flat-ui-master/flat-ui-master/js/application.js" />
/// <reference path="../" />
/// <reference path="../images/новая папка/flat-ui-master/flat-ui-master/js/bootstrap-select.js" />
/// <reference path="../" />
/// <reference path="../images/новая папка/flat-ui-master/flat-ui-master/js/bootstrap-switch.js" />
/// <reference path="../" />
/// <reference path="../images/новая папка/flat-ui-master/flat-ui-master/js/bootstrap-typeahead.js" />
/// <reference path="../" />
/// <reference path="../" />
/// <reference path="../images/новая папка/flat-ui-master/flat-ui-master/js/flatui-checkbox.js" />
/// <reference path="../" />
/// <reference path="../images/новая папка/flat-ui-master/flat-ui-master/js/flatui-radio.js" />
/// <reference path="../" />
/// <reference path="../images/новая папка/flat-ui-master/flat-ui-master/js/html5shiv.js" />
/// <reference path="../" />
/// <reference path="../images/новая папка/flat-ui-master/flat-ui-master/js/icon-font-ie7.js" />
/// <reference path="../" />
/// <reference path="../" />
/// <reference path="../" />
/// <reference path="../" />
/// <reference path="../" />
/// <reference path="../images/новая папка/flat-ui-master/flat-ui-master/js/jquery.placeholder.js" />
/// <reference path="../" />
/// <reference path="../images/новая папка/flat-ui-master/flat-ui-master/js/jquery.stacktable.js" />
/// <reference path="../" />
/// <reference path="../images/новая папка/flat-ui-master/flat-ui-master/js/jquery.tagsinput.js" />
/// <reference path="../" />
/// <reference path="../" />
/// <reference path="../images/новая папка/flat-ui-master/flat-ui-master/bootstrap/js/application.js" />
/// <reference path="../" />
/// <reference path="../images/новая папка/flat-ui-master/flat-ui-master/bootstrap/js/holder.js" />
/// <reference path="../" />
/// <reference path="../images/новая папка/flat-ui-master/flat-ui-master/bootstrap/js/google-code-prettify/prettify.js" />
/// <reference path="../" />
/// <reference path="createcard/jquery.json-2.2.js" />
/// <reference path="../images/новая папка/flat-ui-master/flat-ui-master/js/jquery.ui.touch-punch.js" />
/// <reference path="../images/новая папка/flat-ui-master/flat-ui-master/js/jquery-ui-1.10.3.custom.js" />
/// <reference path="../images/новая папка/flat-ui-master/flat-ui-master/js/jquery-2.0.3.js" />
/// <reference path="../images/новая папка/flat-ui-master/flat-ui-master/js/jquery-1.8.3.js" />
/// <reference path="../images/новая папка/flat-ui-master/flat-ui-master/js/jquery-1.10.2.js" />
/// <reference path="../images/новая папка/flat-ui-master/flat-ui-master/js/bootstrap.js" />
/// <reference path="../" />
