// <auto-generated />
namespace Pass.Container.Repository.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class M15 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(M15));
        
        string IMigrationMetadata.Id
        {
            get { return "201506141523015_M15"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
