// <auto-generated />
namespace Pass.Container.Repository.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class M18 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(M18));
        
        string IMigrationMetadata.Id
        {
            get { return "201506242348142_M18"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
