// <auto-generated />
namespace Pass.Manager.Repository.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class M10 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(M10));
        
        string IMigrationMetadata.Id
        {
            get { return "201411041802375_M10"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
